/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bab10;

/**
 *
 * @author waka I
 */
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.Period;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import javax.swing.JOptionPane;

public class GUI_Pendonor extends javax.swing.JFrame {

    /**
     * Creates new form GUI_BajuAdat
     */
    public GUI_Pendonor() {
        initComponents();
    }
    
    private int hitungUmur(int tglLahir) {
        LocalDate sekarang = LocalDate.now();
        LocalDate tglLahirObj = LocalDate.of(
                tglLahir / 10000,
                (tglLahir % 10000) / 100,
                tglLahir % 100
        );
        return Period.between(tglLahirObj, sekarang).getYears();
    }
    
    private HistoryPendonor historyPendonor = new HistoryPendonor();
    
    private boolean isKabisat(int tahun) {
        return (tahun % 4 == 0 && tahun % 100 != 0) || (tahun % 400 == 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Nama = new javax.swing.JTextField();
        txt_GolonganDarah = new javax.swing.JTextField();
        txt_TanggalLahir = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Output = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txt_TanggalDonorBaru = new javax.swing.JTextField();
        btnSisaHari = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_SisaHari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Pendonor");

        jLabel2.setText("Nama");

        jLabel3.setText("Golongan Darah");

        jLabel4.setText("Tanggal Lahir");

        txt_TanggalLahir.setToolTipText("yyyymmdd");

        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        txt_Output.setColumns(20);
        txt_Output.setRows(5);
        jScrollPane1.setViewportView(txt_Output);

        jLabel5.setText("Tanggal Donor Baru");

        txt_TanggalDonorBaru.setToolTipText("yyyymmdd");

        btnSisaHari.setText("Hitung Sisa Hari");
        btnSisaHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSisaHariActionPerformed(evt);
            }
        });

        jLabel6.setText("Sisa Hari Boleh Donor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_GolonganDarah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TanggalDonorBaru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_SisaHari, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSisaHari)
                        .addGap(18, 18, 18)
                        .addComponent(btnCetak)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_GolonganDarah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_TanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_TanggalDonorBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(btnSisaHari)
                        .addComponent(btnCetak))
                    .addComponent(txt_SisaHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        try {
            String nama = txt_Nama.getText().trim();
            String golonganDarah = txt_GolonganDarah.getText().trim().toUpperCase();
            String inputTgl = txt_TanggalLahir.getText().trim();

            // Validasi input kosong
            if (nama.isEmpty() || golonganDarah.isEmpty() || inputTgl.isEmpty()) {
                throw new IllegalArgumentException("Semua field wajib diisi.");
            }

            // Validasi format golongan darah
            if (!golonganDarah.matches("^(A|B|AB|O)[+-]$")) {
                throw new IllegalArgumentException("Format golongan darah salah! Contoh: A+, B-, AB+, O-");
            }

            // Validasi panjang tanggal
            if (!inputTgl.matches("\\d{8}")) {
                throw new NumberFormatException("Tanggal lahir harus 8 digit dengan format: yyyymmdd.");
            }

            int yyyy = Integer.parseInt(inputTgl.substring(0, 4));
            int mm = Integer.parseInt(inputTgl.substring(4, 6));
            int dd = Integer.parseInt(inputTgl.substring(6, 8));

            // Validasi tanggal
            LocalDate tanggalLahir = LocalDate.of(yyyy, mm, dd);
            int umur = Period.between(tanggalLahir, LocalDate.now()).getYears();
            boolean layak = umur >= 17;

            Pendonor pd = new Pendonor();
            pd.setNama(nama);
            pd.setGolonganDarah(golonganDarah);
            pd.setTanggalLahir(Integer.parseInt(inputTgl));

            // Format tanggal tampil
            String formattedTgl = String.format("%02d-%02d-%04d", dd, mm, yyyy);

            // Output
            txt_Output.setText("");
            txt_Output.append("\tHasil Pengecekan\n");
            txt_Output.append("========================\n");
            txt_Output.append("Nama: " + pd.getNama() + "\n");
            txt_Output.append("Umur: " + umur + " tahun\n");
            txt_Output.append("Gol. Darah: " + pd.getGolonganDarah() + "\n");
            txt_Output.append("Tgl Lahir: " + formattedTgl + "\n");

            if (layak) {
                txt_Output.append("Status: BOLEH DONOR\n");
            } else {
                txt_Output.append("Status: TIDAK BOLEH DONOR\n");
                JOptionPane.showMessageDialog(this, "Pendonor belum cukup umur (minimal 17 tahun).", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }

            String sisaHari = txt_SisaHari.getText().trim();
            if (sisaHari.isEmpty()) {
                sisaHari = "Belum dihitung. Silakan isi tanggal donor baru dan klik tombol 'Sisa Hari'.";
            }
            txt_Output.append("\nInfo Donor:\n" + sisaHari + "\n");

        } catch (DateTimeException dte) {
            JOptionPane.showMessageDialog(this, "Tanggal tidak valid! Cek kembali input tanggal lahir.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, nfe.getMessage(), "Format Salah", JOptionPane.ERROR_MESSAGE);
        } catch (IllegalArgumentException iae) {
            JOptionPane.showMessageDialog(this, iae.getMessage(), "Validasi Gagal", JOptionPane.WARNING_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnSisaHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSisaHariActionPerformed
        // TODO add your handling code here:
        try {
            String tglDonorTerakhir = txt_TanggalDonorBaru.getText().trim();
            String tglDonorBaru = txt_TanggalDonorBaru.getText().trim();

            // Validasi format input (harus 8 digit)
            if (!tglDonorTerakhir.matches("\\d{8}") || !tglDonorBaru.matches("\\d{8}")) {
                throw new NumberFormatException("Format tanggal salah! Gunakan format: yyyymmdd");
            }

            // Parse tanggal donor terakhir
            int yyyy1 = Integer.parseInt(tglDonorTerakhir.substring(0, 4));
            int mm1 = Integer.parseInt(tglDonorTerakhir.substring(4, 6));
            int dd1 = Integer.parseInt(tglDonorTerakhir.substring(6, 8));

            // Parse tanggal donor baru
            int yyyy2 = Integer.parseInt(tglDonorBaru.substring(0, 4));
            int mm2 = Integer.parseInt(tglDonorBaru.substring(4, 6));
            int dd2 = Integer.parseInt(tglDonorBaru.substring(6, 8));

            // Validasi otomatis oleh LocalDate
            LocalDate donorTerakhir = LocalDate.of(yyyy1, mm1, dd1);
            LocalDate donorBaru = LocalDate.of(yyyy2, mm2, dd2);

            long selisihHari = ChronoUnit.DAYS.between(donorTerakhir, donorBaru);

            if (selisihHari < 75) {
                txt_SisaHari.setText("Belum boleh donor lagi. Harap tunggu " + (75 - selisihHari) + " hari lagi.");
            } else {
                txt_SisaHari.setText("Sudah boleh donor. Selisih hari: " + selisihHari + " hari.");
            }

        } catch (DateTimeException dte) {
            JOptionPane.showMessageDialog(this, "Tanggal tidak valid! Cek kembali input.", "Tanggal Salah", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Format tanggal salah! Gunakan format: yyyymmdd", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSisaHariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Pendonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Pendonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Pendonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Pendonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Pendonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnSisaHari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_GolonganDarah;
    private javax.swing.JTextField txt_Nama;
    private javax.swing.JTextArea txt_Output;
    private javax.swing.JTextField txt_SisaHari;
    private javax.swing.JTextField txt_TanggalDonorBaru;
    private javax.swing.JTextField txt_TanggalLahir;
    // End of variables declaration//GEN-END:variables
}
